const STATES = {
  GET_STARTED: 'GET_STARTED',
  REFERRAL_COLLECTION: 'REFERRAL_COLLECTION', // New state for referral code input
  LANGUAGE_SELECTION: 'LANGUAGE_SELECTION',
  NAME_COLLECTION: 'NAME_COLLECTION',
  PATH_SELECTION: 'PATH_SELECTION',
  PATH_A_LOAN_AMOUNT: 'PATH_A_LOAN_AMOUNT',
  PATH_A_TENURE: 'PATH_A_TENURE',
  PATH_A_INTEREST_RATE: 'PATH_A_INTEREST_RATE',
  PATH_B_ORIGINAL_LOAN_AMOUNT: 'PATH_B_ORIGINAL_LOAN_AMOUNT',
  PATH_B_ORIGINAL_TENURE: 'PATH_B_ORIGINAL_TENURE',
  PATH_B_MONTHLY_PAYMENT: 'PATH_B_MONTHLY_PAYMENT',
  PATH_B_YEARS_PAID: 'PATH_B_YEARS_PAID',
  COMPLETE: 'COMPLETE',
  DONE: 'DONE', // New state for marking the flow as finished
};

module.exports = { STATES };
